Repository munich-quantum-toolkit/qmap, pull requests merged in 2022-10, with the labels that each got.

#137 🔧 Codecov Config Update
  .github/codecov.yml
Labels: usability, continuous integration

#142 🐛 temporary workaround for retworkx failure
  setup.py
Labels: bug

#148 📝 Added in-code documentation to `Mapper` and `HeuristicMapper`
  .gitignore
  include/Mapper.hpp
  include/heuristic/HeuristicMapper.hpp
  src/Mapper.cpp
  src/heuristic/HeuristicMapper.cpp
Labels: documentation

#149 📝 Update README
  README.md
Labels: documentation

#151 ✨ Add issue and pull request templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/pull_request_template.md
Labels: usability

#152 :sparkles: Add GitHub community health files
  .github/contributing.rst
  .github/support.rst
Labels: documentation, usability

#153 🔧 Update GitHub to PyPI publish action
  .github/workflows/deploy.yml
Labels: continuous integration, packaging

#154 🐛🔧 Fix and Enhance Codecov Config
  .github/codecov.yml
Labels: bug, usability, continuous integration

#156 📝 Documentation Update
  docs/source/Contributing.rst
  docs/source/DevelopmentGuide.rst
  docs/source/Installation.rst
  docs/source/Library.rst
  docs/source/Support.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/install/Developers.rst
  docs/source/install/Users.rst
  docs/source/library/Library.rst
  noxfile.py
  setup.py
Labels: documentation

#155 🔧 Fixup codecov flag config
  .github/codecov.yml
Labels: bug, continuous integration
