Repository munich-quantum-toolkit/qmap, pull requests merged in 2022-12, with the labels that each got.

#195 🐛 Fix broken sdist CI (caused by switch to Ubuntu 22.04)
  .github/workflows/deploy.yml
Labels: bug, continuous integration

#197 🍱 Add MQT Logo and support Dark-Mode on RtD
  README.md
  docs/source/_static/custom.css
  docs/source/_static/mqt_dark.png
  docs/source/_static/mqt_light.png
  docs/source/conf.py
  pyproject.toml
Labels: documentation

#198 🚨🐛 Disable opinionated bugbear warning
  .flake8
Labels: bug

#199 🔥 Remove Z3 from build dependencies
  .readthedocs.yaml
  pyproject.toml
Labels: dependencies, continuous integration, packaging

#191 🐍 Python Bindings for Clifford Synthesis
  mqt/qmap/CMakeLists.txt
  mqt/qmap/__init__.py
  mqt/qmap/bindings.cpp
  mqt/qmap/clifford_synthesis.py
  mqt/qmap/pyqmap.pyi
  src/cliffordsynthesis/Tableau.cpp
  test/python/test_cliffordsynthesis.py
Labels: feature, python

#202 🐛 fix missing macOS x86 wheels
  .github/workflows/deploy.yml
Labels: bug, continuous integration, packaging

#201 📝 Documentation
  README.md
  docs/source/Publications.rst
  docs/source/Synthesis.ipynb
  docs/source/index.rst
  docs/source/library/Library.rst
  docs/source/library/Synthesis.rst
  docs/source/library/SynthesisResults.rst
  docs/source/refs.bib
Labels: documentation

#196 🎉 Optimal Clifford Synthesis
  .gitmodules
  README.md
  docs/source/Publications.rst
  docs/source/Synthesis.ipynb
  docs/source/index.rst
  docs/source/library/Library.rst
  docs/source/library/Synthesis.rst
  docs/source/library/SynthesisResults.rst
  docs/source/refs.bib
  include/cliffordsynthesis/CliffordSynthesizer.hpp
  include/cliffordsynthesis/Configuration.hpp
  include/cliffordsynthesis/Results.hpp
  include/cliffordsynthesis/TargetMetric.hpp
  include/cliffordsynthesis/encoding/GateEncoder.hpp
  include/cliffordsynthesis/encoding/MultiGateEncoder.hpp
  include/cliffordsynthesis/encoding/ObjectiveEncoder.hpp
  include/cliffordsynthesis/encoding/SATEncoder.hpp
  include/cliffordsynthesis/encoding/SingleGateEncoder.hpp
  include/cliffordsynthesis/encoding/TableauEncoder.hpp
  mqt/qmap/CMakeLists.txt
  mqt/qmap/__init__.py
  mqt/qmap/bindings.cpp
  mqt/qmap/clifford_synthesis.py
  mqt/qmap/pyqmap.pyi
  src/CMakeLists.txt
  src/cliffordsynthesis/CliffordSynthesizer.cpp
  src/cliffordsynthesis/Tableau.cpp
  src/cliffordsynthesis/encoding/GateEncoder.cpp
  src/cliffordsynthesis/encoding/MultiGateEncoder.cpp
  src/cliffordsynthesis/encoding/ObjectiveEncoder.cpp
  src/cliffordsynthesis/encoding/SATEncoder.cpp
  src/cliffordsynthesis/encoding/SingleGateEncoder.cpp
  src/cliffordsynthesis/encoding/TableauEncoder.cpp
  test/CMakeLists.txt
  test/cliffordsynthesis/circuits.json
  test/cliffordsynthesis/tableaus.json
  test/cliffordsynthesis/test_synthesis.cpp
  test/python/test_cliffordsynthesis.py
Labels: feature, python, c++
