Repository munich-quantum-toolkit/qmap, pull requests merged in 2022-09, with the labels that each got.

#98 📝 Initialize Documentation on ReadTheDocs
  .readthedocs.yaml
  docs/Makefile
  docs/make.bat
  docs/source/conf.py
  docs/source/index.rst
  docs/source/refs.bib
  noxfile.py
  setup.py
Labels: documentation

#99 🔧 Fix RtD Documentation Setup
  .readthedocs.yaml
  setup.py
Labels: bug, documentation

#100 🐛 Fix Editable Installations
  setup.py
Labels: bug

#101 ✨ Add pre-commit configuration
  .clang-format
  .cmake-format.yaml
  .flake8
  .github/codecov.yml
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy.yml
  .pre-commit-config.yaml
  .readthedocs.yaml
  CMakeLists.txt
  README.md
  apps/CMakeLists.txt
  cmake/FindZ3.cmake
  examples/qe_qft_4.qasm
  examples/qe_qft_5.qasm
  include/heuristic/unique_priority_queue.hpp
  include/utils.hpp
  jkq/__init__.py
  mqt/qmap/CMakeLists.txt
  mqt/qmap/__init__.py
  mqt/qmap/compile.py
  mqt/qmap/qiskit/backend.py
  noxfile.py
  pyproject.toml
  setup.py
  src/CMakeLists.txt
  test/CMakeLists.txt
  test/python/test.py
  test/python/test_exact_mapper.py
  test/python/test_heuristic_mapper.py
  test/python/test_qiskit_backend_imports.py
Labels: enhancement, dependencies

#104 🔧 Proper Versioning in Deploy CI
  .github/workflows/deploy.yml
Labels: bug

#108 🔧 Add in-progress cancellation to CI workflows
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy.yml
Labels: usability, continuous integration

#107 🔧 Update CodeQL configuration
  .github/codeql-config.yml
  .github/workflows/codeql-analysis.yml
  include/heuristic/HeuristicMapper.hpp
  mqt/qmap/bindings.cpp
  src/heuristic/HeuristicMapper.cpp
Labels: github_actions, usability, continuous integration

#109 ⬆️ Update Z3 from version `4.8.17` to `4.11.2`
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  pyproject.toml
Labels: dependencies

#103 ✨ Optionally disable measurements
  include/configuration/Configuration.hpp
  mqt/qmap/bindings.cpp
  mqt/qmap/compile.py
  src/Mapper.cpp
  test/test_exact.cpp
  test/test_heuristic.cpp
Labels: feature

#111 🐛 Fix version check for Z3 when cross compiling
  cmake/FindZ3.cmake
Labels: bug, usability

#110 🐍 Python Testing Setup
  .github/workflows/python-ci.yml
  CMakeLists.txt
  mqt/qmap/compile.py
  noxfile.py
  pyproject.toml
  setup.py
  src/Architecture.cpp
  test/python/test_compile.py
  test/python/test_exact_mapper.py
  test/python/test_heuristic_mapper.py
  test/python/test_qiskit_backend_imports.py
Labels: python, continuous integration

#114 📝 Docs
  docs/source/Installation.rst
  docs/source/Library.rst
  docs/source/Mapping.rst
  docs/source/Publications.rst
  docs/source/images/linear_arch.svg
  docs/source/index.rst
  docs/source/install/Developers.rst
  docs/source/install/Users.rst
  docs/source/library/Architecture.rst
  docs/source/library/Mapping.rst
  docs/source/library/MappingResults.rst
  docs/source/refs.bib
  mqt/qmap/bindings.cpp
  mqt/qmap/compile.py
Labels: documentation

#112 👷 Streamline Z3 Configuration
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy.yml
  .github/workflows/python-ci.yml
  CMakeLists.txt
  README.md
  cmake/FindZ3.cmake
  mqt/qmap/__init__.py
  pyproject.toml
  test/CMakeLists.txt
Labels: continuous integration

#118 🚨 Further flake8 checks
  .flake8
  .pre-commit-config.yaml
  mqt/qmap/__init__.py
  mqt/qmap/compile.py
  setup.py
  test/python/test_compile.py
Labels: python, usability, continuous integration

#119 📦 Leaner source distribution
  MANIFEST.in
Labels: packaging
