Repository munich-quantum-toolkit/qmap, pull requests merged in 2023-02, with the labels that each got.

#233 🔧 add `merge_group` to workflow configs
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/cpp-linter.yml
  .github/workflows/deploy.yml
  .github/workflows/python-ci.yml
Labels: continuous integration

#232 🔧 mypy configuration update
  .github/workflows/python-ci.yml
  .pre-commit-config.yaml
  noxfile.py
  pyproject.toml
Labels: python, continuous integration

#236 🔧 Add release drafter workflow
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: continuous integration

#234 🚨 Introduce `ruff`
  .flake8
  .pre-commit-config.yaml
  docs/source/_static/custom.css
  docs/source/conf.py
  docs/source/library/Architecture.rst
  mqt/qmap/__init__.py
  mqt/qmap/bindings.cpp
  mqt/qmap/clifford_synthesis.py
  mqt/qmap/compile.py
  mqt/qmap/load_architecture.py
  mqt/qmap/load_calibration.py
  mqt/qmap/pyqmap.pyi
  mqt/qmap/qiskit/backend.py
  mqt/qmap/subarchitectures.py
  noxfile.py
  pyproject.toml
  setup.py
  test/python/test.py
  test/python/test_cliffordsynthesis.py
  test/python/test_compile.py
  test/python/test_exact_mapper.py
  test/python/test_heuristic_mapper.py
  test/python/test_qiskit_backend_imports.py
  test/python/test_subarchitectures.py
Labels: documentation, dependencies, python, continuous integration

#237 📝 Add QMAP overview paper
  README.md
  docs/source/Publications.rst
  docs/source/index.rst
  docs/source/refs.bib
Labels: documentation

#239 🎨 Small dark-mode docs improvement
  docs/source/_static/custom.css
Labels: documentation

#240 Fix disjoint layer
  src/Mapper.cpp
  test/test_heuristic.cpp
Labels: bug

#241 🔊 Enable Logging for Clifford Synthesis
  docs/source/library/Synthesis.rst
  include/cliffordsynthesis/Configuration.hpp
  mqt/qmap/__init__.py
  mqt/qmap/bindings.cpp
  mqt/qmap/pyqmap.pyi
  src/cliffordsynthesis/CliffordSynthesizer.cpp
  test/cliffordsynthesis/test_synthesis.cpp
Labels: feature

#243 🔊 Allow to dump intermediate synthesis results
  include/cliffordsynthesis/Configuration.hpp
  mqt/qmap/bindings.cpp
  mqt/qmap/pyqmap.pyi
  src/cliffordsynthesis/CliffordSynthesizer.cpp
  test/cliffordsynthesis/test_synthesis.cpp
Labels: feature

#245 Dijkstra node order bug fix
  include/utils.hpp
  src/utils.cpp
Labels: bug

#249 Fix A* node ordering
  include/heuristic/HeuristicMapper.hpp
Labels: bug

#248 adding Disjoint2qBlocks layering
  include/Mapper.hpp
  include/configuration/Layering.hpp
  mqt/qmap/bindings.cpp
  mqt/qmap/pyqmap.pyi
  src/Mapper.cpp
  test/test_exact.cpp
  test/test_heuristic.cpp
Labels: feature
