Repository munich-quantum-toolkit/qmap, pull requests merged in 2023-03, with the labels that each got.

#252 🐛 Fix cost contribution of direction reverse in exact mapper
  src/exact/ExactMapper.cpp
  test/test_exact.cpp
Labels: bug

#262 🐛 Fixed bug in Clifford circuit tableau simulation
  src/cliffordsynthesis/Tableau.cpp
  test/test_tableau.cpp
Labels: bug

#264 🐛 Fix performance regression in exact mapper on directed architectures
  include/Architecture.hpp
  include/configuration/Configuration.hpp
  src/Architecture.cpp
  src/exact/ExactMapper.cpp
  test/test_exact.cpp
Labels: bug

#271 🩹 change PyPI upload option to kebab-case
  .github/workflows/deploy.yml
Labels: dependencies, continuous integration

#272 🔧 Update Release Drafter Configuration
  .github/release-drafter.yml
Labels: continuous integration

#270 ⬆️🪝 Update ruff and use automatic `target-version` inference
  .pre-commit-config.yaml
  mqt/qmap/subarchitectures.py
  pyproject.toml
  setup.py
  test/python/test_compile.py
  test/python/test_exact_mapper.py
  test/python/test_heuristic_mapper.py
  test/python/test_qiskit_backend_imports.py
Labels: dependencies, code quality

#269 Dijkstra arbitrary weights
  include/Architecture.hpp
  include/utils.hpp
  src/Architecture.cpp
  src/utils.cpp
  test/test_general.cpp
Labels: usability

#274 ♻️ Refactor heuristic mapper
  include/heuristic/HeuristicMapper.hpp
  src/heuristic/HeuristicMapper.cpp
  test/test_heuristic.cpp
Labels: usability

#279 Test heuristic for admissibility
  test/test_heuristic.cpp
Labels: c++, code quality

#278 Heuristic Benchmarking
  docs/source/library/MappingResults.rst
  include/MappingResults.hpp
  include/configuration/Configuration.hpp
  include/heuristic/HeuristicMapper.hpp
  mqt/qmap/bindings.cpp
  mqt/qmap/compile.py
  mqt/qmap/pyqmap.pyi
  src/configuration/Configuration.cpp
  src/heuristic/HeuristicMapper.cpp
  test/test_heuristic.cpp
Labels: c++, code quality
