Repository munich-quantum-toolkit/qmap, pull requests merged in 2024-11, with the labels that each got.

#559 🐛 Fix test suite regression in heuristic mapper
  test/sc/heuristic/test_heuristic.cpp
Labels: c++, fix

#500 Integrate Neutral Atom State Preparation
  cmake/ExternalDependencies.cmake
  include/na/Architecture.hpp
  include/na/Configuration.hpp
  include/na/nalac/NAGraphAlgorithms.hpp
  include/na/nalac/NAMapper.hpp
  include/na/nasp/CodeGenerator.hpp
  include/na/nasp/Solver.hpp
  include/na/nasp/SolverFactory.hpp
  src/na/Architecture.cpp
  src/na/CMakeLists.txt
  src/na/Configuration.cpp
  src/na/nalac/CMakeLists.txt
  src/na/nalac/NAGraphAlgorithms.cpp
  src/na/nalac/NAMapper.cpp
  src/na/nasp/CMakeLists.txt
  src/na/nasp/CodeGenerator.cpp
  src/na/nasp/Solver.cpp
  src/na/nasp/SolverFactory.cpp
  test/na/CMakeLists.txt
  test/na/nalac/CMakeLists.txt
  test/na/nalac/test_nagraphalgorithms.cpp
  test/na/nalac/test_namapper.cpp
  test/na/nasp/CMakeLists.txt
  test/na/nasp/circuits/steane.qasm
  test/na/nasp/test_codegenerator.cpp
  test/na/nasp/test_solver.cpp
  test/na/nasp/test_solverfactory.cpp
  test/na/test_architecture.cpp
Labels: feature, c++, minor

#556 🚸 Python Bindings for NA State Preparation
  docs/DevelopmentGuide.rst
  docs/NAStatePrep.ipynb
  docs/Publications.rst
  docs/index.rst
  docs/library/Library.rst
  docs/library/NAStatePrep.rst
  docs/refs.bib
  include/na/nasp/CodeGenerator.hpp
  include/na/nasp/Solver.hpp
  pyproject.toml
  src/mqt/qmap/na/__init__.py
  src/mqt/qmap/na/state_preparation.py
  src/mqt/qmap/pyqmap.pyi
  src/na/nasp/CodeGenerator.cpp
  src/na/nasp/Solver.cpp
  src/python/CMakeLists.txt
  src/python/bindings.cpp
  test/na/nasp/circuits/shor.qasm
  test/na/nasp/circuits/surface_3.qasm
  test/na/nasp/test_codegenerator.cpp
  test/na/nasp/test_solver.cpp
  test/python/na/test_state_preparation.py
Labels: python, usability
