Repository munich-quantum-toolkit/qmap, pull requests merged in 2025-05, with the labels that each got.

#644 🩹 avoid spurious upstream failures on cancellation
  .github/workflows/upstream.yml
Labels: continuous integration, fix

#645 📝 Add changelog and upgrade guide
  .github/release-drafter.yml
  CHANGELOG.md
  UPGRADING.md
  docs/CHANGELOG.md
  docs/UPGRADING.md
  docs/conf.py
  docs/index.md
Labels: documentation

#646 📝 Update Issue and PR templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/pull_request_template.md
Labels: documentation

#650 ✏️ Fix broken links in changelog
  CHANGELOG.md
Labels: documentation

#661 🐛 Fix CD
  CHANGELOG.md
  include/na/zoned/Compiler.hpp
  src/na/zoned/reuse_analyzer/VertexMatchingReuseAnalyzer.cpp
Labels: documentation, continuous integration, packaging, fix, extensive-python-ci
