Repository munich-quantum-toolkit/qmap, pull requests merged in 2025-03, with the labels that each got.

#604 ⬆️ scikit-build-core 0.11, PEP 639 license expressions, sphinx fixes, more automerge
  .github/renovate.json5
  .pre-commit-config.yaml
  noxfile.py
  pyproject.toml
  src/mqt/qmap/subarchitectures.py
  uv.lock
Labels: dependencies, python

#609 🏗️ Remove SolverFactory to entirely isolate NALAC
  include/na/nasp/Solver.hpp
  include/na/nasp/SolverFactory.hpp
  src/na/nasp/CMakeLists.txt
  src/na/nasp/Solver.cpp
  src/na/nasp/SolverFactory.cpp
  src/python/bindings.cpp
  test/na/nasp/test_codegenerator.cpp
  test/na/nasp/test_solver.cpp
  test/na/nasp/test_solverfactory.cpp
Labels: dependencies, refactor

#610 ✨Add continuous testing workflow for Qiskit main branch
  .github/workflows/upstream.yml
  noxfile.py
  src/mqt/qmap/load_calibration.py
  src/mqt/qmap/plugins/qiskit.py
  test/python/test_qiskit_backend_imports.py
Labels: dependencies, github_actions, python, continuous integration

#614 ✨📝 Revamp documentation
  .github/contributing.md
  .github/contributing.rst
  .github/support.md
  .github/support.rst
  .pre-commit-config.yaml
  .readthedocs.yaml
  README.md
  docs/Contributing.rst
  docs/DevelopmentGuide.rst
  docs/Installation.rst
  docs/Mapping.ipynb
  docs/NAStatePrep.ipynb
  docs/Publications.rst
  docs/Support.rst
  docs/Synthesis.ipynb
  docs/_static/custom.css
  docs/conf.py
  docs/contributing.md
  docs/development_guide.md
  docs/index.md
  docs/index.rst
  docs/installation.md
  docs/library/Architecture.rst
  docs/library/Library.rst
  docs/library/Mapping.rst
  docs/library/MappingResults.rst
  docs/library/NAStatePrep.rst
  docs/library/Subarchitectures.rst
  docs/library/Synthesis.rst
  docs/library/SynthesisResults.rst
  docs/library/Visualization.rst
  docs/lit_header.bib
  docs/mapping.md
  docs/na_state_prep.md
  docs/references.md
  docs/refs.bib
  docs/support.md
  docs/synthesis.md
  pyproject.toml
  src/mqt/qmap/__init__.py
  src/mqt/qmap/clifford_synthesis.py
  src/mqt/qmap/compile.py
  src/mqt/qmap/plugins/qiskit.py
  src/mqt/qmap/pyqmap.pyi
  src/mqt/qmap/subarchitectures.py
  test/python/test_cliffordsynthesis.py
  test/python/test_compile.py
  test/python/test_hybridmap.py
  test/python/test_subarchitectures.py
  uv.lock
Labels: documentation
