Repository munich-quantum-toolkit/qmap, pull requests merged in 2025-07, with the labels that each got.

#692 👷 Enable templating
  .github/workflows/templating.yml
Labels: continuous integration

#701 🔖 Prepare release of v3.2.0
  CHANGELOG.md
  UPGRADING.md
Labels: documentation

#712 🐛 Fix out-of-bounds access to reuse qubits
  .github/workflows/ci.yml
  CHANGELOG.md
  src/na/zoned/placer/VertexMatchingPlacer.cpp
Labels: c++, fix, extensive-cpp-ci

#714 🎨 Do not rebuild MQT Core in tests
  .readthedocs.yaml
  CHANGELOG.md
  UPGRADING.md
  noxfile.py
Labels: python, fix

#715 ✨ Make Python enums PEP-435 compatible
  CHANGELOG.md
  UPGRADING.md
  bindings/clifford_synthesis/CMakeLists.txt
  bindings/clifford_synthesis/clifford_synthesis.cpp
  bindings/hybrid_mapper/CMakeLists.txt
  bindings/hybrid_mapper/hybrid_mapper.cpp
  bindings/sc/CMakeLists.txt
  bindings/sc/sc.cpp
  docs/mapping.md
  docs/synthesis.md
  python/mqt/qmap/clifford_synthesis.pyi
  python/mqt/qmap/hybrid_mapper.pyi
  python/mqt/qmap/plugins/qiskit/sc/compile.py
  python/mqt/qmap/sc.pyi
  test/python/clifford_synthesis/test_clifford_synthesis.py
  test/python/sc/test_compile.py
  test/python/sc/test_exact_mapper.py
Labels: python, c++, enhancement, minor

#716 Fix minor typos
  python/mqt/qmap/clifford_synthesis.pyi
  python/mqt/qmap/na/state_preparation.pyi
  python/mqt/qmap/plugins/qiskit/sc/compile.py
Labels: documentation, code quality

#713 ♻️ Merge Placement and Routing into Layout Synthesis
  CHANGELOG.md
  UPGRADING.md
  bindings/na/zoned/zoned.cpp
  include/na/zoned/Compiler.hpp
  include/na/zoned/layout_synthesizer/LayoutSynthesizerBase.hpp
  include/na/zoned/layout_synthesizer/PlaceAndRouteSynthesizer.hpp
  include/na/zoned/layout_synthesizer/placer/AStarPlacer.hpp
  include/na/zoned/layout_synthesizer/placer/PlacerBase.hpp
  include/na/zoned/layout_synthesizer/placer/VertexMatchingPlacer.hpp
  include/na/zoned/layout_synthesizer/router/IndependentSetRouter.hpp
  include/na/zoned/layout_synthesizer/router/RouterBase.hpp
  src/na/zoned/layout_synthesizer/placer/AStarPlacer.cpp
  src/na/zoned/layout_synthesizer/placer/VertexMatchingPlacer.cpp
  src/na/zoned/layout_synthesizer/router/IndependentSetRouter.cpp
  test/na/zoned/test_a_star_placer.cpp
  test/na/zoned/test_compiler.cpp
  test/na/zoned/test_independent_set_router.cpp
  test/na/zoned/test_vertex_matching_placer.cpp
Labels: c++, minor, refactor
